### ISSUE TITLE
"/tf" vs "tf"

### ISSUE THREAD

**Issue by gondsm** [marcoesposito1988/tf_bag#1]
Hello!

First of all, thank you very much for the awesome package; it saved me a ton of headache!

I had some trouble loading up the messages from my bag (recorded in ROS Indigo) due to the line

```
self.tf_messages = sorted((tm for m in bag if m.topic == '/tf' for tm in m.message.transforms),
key=lambda tfm: tfm.header.stamp.to_nsec())
```

EDIT: I recorded my bag by running `rosbag record odom tf`.

(which can be found [here](https://github.com/IFL-CAMP/tf_bag/blob/master/src/tf_bag.py#L25) in your code)

This only allows for messages under the "/tf" topic. However, for whatever reason, my bag's topic is "tf" and not "/tf". I'm not sure whether I made some mistake when recording it, but the fact is that changing your code to "tf" fixed the issue, and I can read the info I need from the bag effortlessly.

Is this some sort of mismatch in ROS versions? Should this be accounted for in the package? If you think so, I'd be happy to submit a pull request that implements compatibility with both topic names.

**Comment by marcoesposito1988** [comment]
Hi @gondsm,

great, I'm happy you found the package useful!

That may depend on how you specified the tf topic in the rosbag record command list.. maybe I was doing `rosbag record /tf` and you are doing `rosbag record tf`... anyway, this shouldn't happen, thanks a lot for reporting this problem!

I think this could be fixed with `if m.topic.strip('/') == 'tf'` (or something in that direction, I'm writing from my phone). Would you feel like testing it and creating a pull request?

**Comment by gondsm** [comment]
Hey @marcoesposito1988, thanks for the reply!

I'm actively working on something that now depends on `tf_bag`, so I'll be happy to do some side testing and contribute a PR. I'll try to get it done sometime today.

**Comment by gondsm** [comment]
Thanks @marcoesposito1988 for the quick reply. I submitted pull request #2 which fixes the problem on my tests.

I meant to do it yesterday, but yesterday was hectic ;)
